### ISSUE TITLE
First commit does not include ~=[,,_,,]:3

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/fundraising-frontend-content#1]
The message of the first commit (https://github.com/wmde/fundraising-frontend-content/commit/23f9b2870b72fa73783215f70c57c90a94683c0a) does not include a NyanCat. Clearly someone should be send to a git 101 course... maw

**Comment by gbirke** [comment]
WONTFIX: Since this repo is now deployed, we can't modify/rebase/amend the master anymore.
